test(wip): test config gh cli action

diff --git a/test/config-gh-cli/action.yml b/test/config-gh-cli/action.yml
--- a/test/config-gh-cli/action.yml
+++ b/test/config-gh-cli/action.yml
@@ -12,9 +12,12 @@ branding:
 # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
 inputs:
   account-type:
-    description: 'The type of account to use, either `bot` or `user`.'
+    description: 'The type of GitHub account to use, either `bot` (GitHub App) or `user` (GitHub User Account).'
     required: true
     #default: 'bot'
+  gh-app-id:
+    description: 'The GitHub App ID used to authenticate to the GitHub CLI.'
+    required: false
   gh-app-key:
     description: 'The GitHub App Key used to authenticate to the GitHub CLI.'
     required: false
@@ -23,6 +26,7 @@ inputs:
     description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT) used to authenticate to the GitHub CLI.'
     required: false
     default: ${{ github.token }}
+    # user: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
   verbose:
     description: 'Determine if the action should run verbose tasks, defaults to false.'
     required: false
@@ -98,7 +102,7 @@ runs:
         GH_TOKEN: ${{ inputs.gh-token }}
       run: |
         echo "Login with the user actions token "
-        echo ${{ secrets.BOT_USER_ACTIONS_TOKEN }} | gh auth login --with-token
+        echo ${{ inputs.gh-token }} | gh auth login --with-token
         echo ""
         echo "Check the GitHub authentication status "
         gh auth status
@@ -111,10 +115,8 @@ runs:
       # GitHub Action for creating a GitHub App installation access token.
       uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
       id: app-token
-      #if: ${{ steps.pr-from-commit.outputs.result && fromJson(steps.pr-from-commit.outputs.result).number }}
       # this worked when we were using the 'bot' for authentication
       if: inputs.account-type=='bot'
-      #if: ${{ steps.pr-from-commit.outputs.result && fromJson(steps.pr-from-commit.outputs.result).number && inputs.account-type=='bot' }}
       with:
         # required
         app-id: ${{ secrets.GH_APP_ID }}
@@ -122,6 +124,92 @@ runs:
         # create a token for all repositories in the current owner's installation
         # https://github.com/actions/create-github-app-token#create-a-token-for-all-repositories-in-the-current-owners-installation
         owner: ${{ github.repository_owner }}
+
+
+    - name: Check GitHub auth status
+      id: check-github-auth
+      env:
+        # use GH_TOKEN per https://josh-ops.com/posts/gh-auth-login-in-actions/
+        #bot#GH_TOKEN: ${{ inputs.gh-app-key }}
+        #user#GH_TOKEN: ${{ inputs.gh-token }}
+        GH_TOKEN: ${{ inputs.gh-token }}
+        #
+        #bot#GITHUB_TOKEN: ${{ inputs.gh-app-key }}
+        #user#GITHUB_TOKEN: ${{ inputs.gh-token }}
+      run: |
+        echo "Check the GitHub authentication status "
+        gh auth status
+        echo ""
+      shell: bash
+
+
+    - name: Get the GitHub User ID
+      id: gh-user-id
+      run: |
+        echo "Get the GitHub User information "
+        cli_user_id=$(gh api user -q ".id")
+        cli_user_login=$(gh api user -q ".login")
+        cli_user_name=$(gh api user -q ".name")
+        cli_user_type=$(gh api user -q ".type")
+        #
+        #
+        if [[ "${GH_LOCAL_PRIMARY}" == "bot" ]]; then
+            # append '[bot]' to the user login
+            cli_user_login="${cli_user_login}[bot]"
+        elif [[ "${GH_LOCAL_PRIMARY}" == "user" ]]; then
+            # do nothing, maybe set cli_user_login again
+            cli_user_login="${cli_user_login}"
+        else
+            echo "this workflow will now fail"
+            exit 1
+        fi
+        #
+        cli_user_email="${cli_user_id}+${cli_user_login}@users.noreply.github.com"
+        #
+        #
+        # Print user information
+        echo "the user ID is ${cli_user_id} "
+        echo "the user type is ${cli_user_type} "
+        echo "the user name is ${cli_user_name} "
+        echo "the user login is ${cli_user_login} "
+        echo "the user email is ${cli_user_email} "
+        #
+        # Output the user information
+        echo "user-id=${cli_user_id}" >> "$GITHUB_OUTPUT"
+        echo "user-login=${cli_user_login}" >> "$GITHUB_OUTPUT"
+        echo "user-name=${cli_user_name}" >> "$GITHUB_OUTPUT"
+        echo "user-type=${cli_user_type}" >> "$GITHUB_OUTPUT"
+        echo "user-email=${cli_user_email}" >> "$GITHUB_OUTPUT"
+        # 
+        echo ""
+        #
+        echo "consolidate this with the 'configure-git' step"
+      env:
+        # use GH_TOKEN per https://josh-ops.com/posts/gh-auth-login-in-actions/
+        #bot#GH_TOKEN: ${{ inputs.gh-app-key }}
+        #user#GH_TOKEN: ${{ inputs.gh-token }}
+        GH_TOKEN: ${{ inputs.gh-token }}
+        #
+        #bot#GITHUB_TOKEN: ${{ inputs.gh-app-key }}
+        #user#GITHUB_TOKEN: ${{ inputs.gh-token }}
+      shell: bash
+
+
+    - name: Configure git for the GitHub user
+      id: configure-git
+      run: |
+        git config --global user.name '${{ steps.gh-user-id.outputs.user-name }}'
+        git config --global user.email '${{ steps.gh-user-id.outputs.user-email }}'
+        echo "consolidate this with the 'gh-user-id' step"
+      env:
+        # use GH_TOKEN per https://josh-ops.com/posts/gh-auth-login-in-actions/
+        #bot#GH_TOKEN: ${{ inputs.gh-app-key }}
+        #user#GH_TOKEN: ${{ inputs.gh-token }}
+        GH_TOKEN: ${{ inputs.gh-token }}
+        #
+        #bot#GITHUB_TOKEN: ${{ inputs.gh-app-key }}
+        #user#GITHUB_TOKEN: ${{ inputs.gh-token }}
+      shell: bash
 
 
     - name: Output variables from this job to the action output
