test: second draft of the get-next-semver action

diff --git a/test/get-next-semver/action.yml b/test/get-next-semver/action.yml
--- a/test/get-next-semver/action.yml
+++ b/test/get-next-semver/action.yml
@@ -8,25 +8,6 @@ branding:
   # fork: https://github.com/rwaight/github-action-brandings
 
 inputs:
-
-  # gh-token:
-  #   description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT), may be needed for the GitHub CLI. '
-  #   required: true
-  #   default: ${{ github.token }}
-  # gh-setup:
-  #   description: 'Determine if the action should setup git with `git config`, defaults to false. '
-  #   required: false
-  #   default: 'false'
-  # gh-user-name:
-  #   description: 'The GitHub user name for committing changes to the JSON vars file. '
-  #   required: false
-  #   #   keep 'github-actions[bot]' as default
-  #   default: 'github-actions[bot]'
-  # gh-user-email:
-  #   description: 'The GitHub user email for committing changes to the JSON vars file. '
-  #   required: false
-  #   #   keep '<41898282+github-actions[bot]@users.noreply.github.com>' as default
-  #   default: '<41898282+github-actions[bot]@users.noreply.github.com>'
   pre-release-id:
     description: 'Pre-release identifier (only for pre-release builds). The only supported pre-release syntax is "rc" at this time. '
     required: false
@@ -303,6 +284,12 @@ runs:
         fi
         echo "does_current_match_next=${current_and_next_match}" >> "$GITHUB_OUTPUT"
         echo "does_current_match_next=${current_and_next_match}" >> $GITHUB_ENV
+        if [ '${{ inputs.my_action_debug }}' == 'true' ]; then
+            echo "The does_current_match_next variable has been set to \`$current_and_next_match\`"
+            echo "writing $current_and_next_match to the 'does-current-match-next' GitHub output"
+        fi
+        echo "does-current-match-next=${current_and_next_match}" >> "$GITHUB_OUTPUT"
+        echo "does-current-match-next=${current_and_next_match}" >> $GITHUB_ENV
         if [ '${{ inputs.my_action_debug }}' == 'true' ]; then echo "completing the 'compare-current-to-next-release' step. "; fi
       env:
         current_release_version: ${{ steps.get-current-release.outputs.current-release-version }}
@@ -318,155 +305,39 @@ runs:
         ##
         if [ '${{ inputs.my_action_debug }}' == 'true' ]; then
             echo "starting the 'error-matched-versions' step. "
+            echo "does-current-match-next is:  ${{ env.does-current-match-next }} "
+            echo "current-release-version is:  ${{ env.current-release-version }} "
+            echo "next-release-version is   :  ${{ env.next-release-version }} "
         fi
-        echo "The current version matches the next version. "
+        echo "::error title=⛔ error hint::The current version matches the next version"
+        exit 1
         if [ '${{ inputs.my_action_debug }}' == 'true' ]; then echo "completing the 'error-matched-versions' step. "; fi
       env: 
-        current_and_next_match: ${{ steps.compare-current-to-next-release.outputs.does_current_match_next }}
+        current-release-version: ${{ steps.get-current-release.outputs.current-release-version }}
+        next-release-version: ${{ steps.set-next-release.outputs.next-release-version }}
+        does-current-match-next: ${{ steps.compare-current-to-next-release.outputs.does-current-match-next }}
 
-    # Require the proper checkout action to be run before this action is called
-    # https://github.com/actions/checkout/?tab=readme-ov-file#push-a-commit-using-the-built-in-token
-    # - name: Set up git config
-    #   id: set-up-git
-    #   if: |
-    #     inputs.gh-setup == 'true' && 
-    #     ( '${{ steps.compare-current-to-next-release.outputs.does_current_match_next }}' != 'true' )
-    #   shell: bash
-    #   run: |
-    #     if [ '${{ inputs.my_action_debug }}' == 'true' ]; then
-    #         echo "starting the 'set-up-git' step. "
-    #         echo "git_user_name is :  ${{ env.git_user_name }} "
-    #         echo "git_user_email is:  ${{ env.git_user_email }} "
-    #     fi
-    #     git --version
-    #     git config user.name "${{ env.git_user_name }}"
-    #     git config user.email "${{ env.git_user_email }}"
-    #     git status
-    #     if [ '${{ inputs.my_action_debug }}' == 'true' ]; then echo "completing the 'set-up-git' step. "; fi
-    #   env:
-    #     git_user_name: ${{ inputs.gh-user-name }}
-    #     git_user_email: ${{ inputs.gh-user-email }}
-
-    - name: Bump the current json version
-      id: bump-current-json-version
+    - name: Validate that the current version does not match the next version
+      id: validate-version-not-matched
       if: ( '${{ steps.compare-current-to-next-release.outputs.does_current_match_next }}' != 'true' )
       shell: bash
       run: |
-        ## Bump the current json version
+        ## Validate that the current version does not match the next version
         ## the double number signs below are for line spacing and readability only
         ##
         if [ '${{ inputs.my_action_debug }}' == 'true' ]; then
-            echo "starting the 'bump-current-json-version' step. "
-            echo "json_vars_file is      :  ${{ env.json_vars_file }} "
-            echo "json_vars_field is     :  ${{ env.json_vars_field }} "
-            echo "next_release_version is:  ${{ env.next_release_version }} "
-            echo ""
-            echo "::group::printing the syntax to set the '${{ env.json_vars_field }}' field to ${{ env.next_release_version }} ... "
-            ## tmp=$(mktemp)
-            ## jq '.my_custom_version = "my-new-value"' my-custom-variables.json > "$tmp" && mv "$tmp" my-custom-variables.json
-            echo "tmp=\$(mktemp)"
-            echo "jq '.my_custom_version = \"my-new-value\"' my-custom-variables.json > \"\$tmp\" && mv \"\$tmp\" my-custom-variables.json\" "
-            echo ""
-            echo "special thanks to whoever posted the commands on stackoverflow... "
-            echo " https://stackoverflow.com/questions/42716734/modify-a-key-value-in-a-json-using-jq-in-place "
-            echo ""
-            echo "::endgroup::"
+            echo "starting the 'validate-version-not-matched' step. "
+            echo "does-current-match-next is:  ${{ env.does-current-match-next }} "
+            echo "current-release-version is:  ${{ env.current-release-version }} "
+            echo "next-release-version is   :  ${{ env.next-release-version }} "
         fi
-        tmp=$(mktemp)
-        jq '.${{ env.json_vars_field }} = "${{ env.next_release_version }}"' ${{ env.json_vars_file }} > "$tmp" && mv "$tmp" ${{ env.json_vars_file }}
+        echo "Excellent, the current version does not match the next version. "
         ##
-        if [ '${{ inputs.my_action_debug }}' == 'true' ]; then
-            echo "going to check the version in the JSON file "
-        fi
-        ##
-        check_json_version=$(jq --raw-output .${{ env.json_vars_field }} ${{ env.json_vars_file }})
-        if [ '${{ inputs.my_action_debug }}' == 'true' ]; then
-            echo "check_json_version: $check_json_version"
-        fi
-        ##
-        if [ '${{ inputs.my_action_debug }}' == 'true' ]; then echo "completing the 'bump-current-json-version' step. "; fi
-      env:
-        json_vars_file: ${{ inputs.json-vars-file }}
-        json_vars_field: ${{ inputs.json-vars-field }}
-        next_release_version: ${{ steps.set-next-release.outputs.next-release-version }}
-
-    - name: Get the updated value of the ${{ inputs.json-vars-field }} version field
-      id: get-updated-version
-      shell: bash
-      run: |
-        ## Get the updated value of the ${{ inputs.json-vars-field }} version field
-        ## the double number signs below are for line spacing and readability only
-        ##
-        if [ '${{ inputs.my_action_debug }}' == 'true' ]; then
-            echo "starting the 'get-updated-version' step. "
-            echo "json_vars_file is :  ${{ env.json_vars_file }} "
-            echo "json_vars_field is:  ${{ env.json_vars_field }} "
-            echo ""
-            echo "the syntax is 'MY_CUSTOM_VERSION=$(jq --raw-output .my_custom_field my-custom-variables.json)' "
-        fi
-        updated_json_version=$(jq --raw-output .${{ env.json_vars_field }} ${{ env.json_vars_file }})
-        if [ '${{ inputs.my_action_debug }}' == 'true' ]; then
-            echo "updated_json_version: $updated_json_version"
-            echo "writing the 'updated_json_version' to the environment and GitHub output"
-        fi
-        ##
-        echo "updated_json_version=$updated_json_version" >> $GITHUB_ENV
-        echo "updated_json_version=$updated_json_version" >> "$GITHUB_OUTPUT"
-        if [ '${{ inputs.my_action_debug }}' == 'true' ]; then
-            echo "writing $updated_json_version to the 'new-json-version' GitHub output"
-        fi
-        echo "new-json-version=$updated_json_version" >> $GITHUB_ENV
-        echo "new-json-version=$updated_json_version" >> "$GITHUB_OUTPUT"
-        ##
-        if [ '${{ inputs.my_action_debug }}' == 'true' ]; then
-            echo "checking to see if the updated_json_version matches the next_release_version "
-        fi
-        if [ '$updated_json_version' == '${{ env.next_release_version }}' ]; then
-            echo "the 'updated_json_version' is set to '$updated_json_version' and matches "
-            echo "  the 'next_release_version' which is set to '${{ env.next_release_version }}'. "
-            next_and_updated_match=true
-        else
-            echo "the 'updated_json_version' is set to '$updated_json_version' and DOES NOT MATCH "
-            echo "  the 'next_release_version' which is set to '${{ env.next_release_version }}'. "
-            next_and_updated_match=false
-        fi
-        ##
-        if [ '${{ inputs.my_action_debug }}' == 'true' ]; then
-            echo "setting the value of 'does_next_match_updated' to '${next_and_updated_match}' and sending it to GitHub output"
-        fi
-        echo "does_next_match_updated=${next_and_updated_match}" >> "$GITHUB_OUTPUT"
-        echo "does_next_match_updated=${next_and_updated_match}" >> $GITHUB_ENV
-        #
-        if [ '${{ inputs.my_action_debug }}' == 'true' ]; then echo "completing the 'get-updated-version' step. "; fi
-      env:
-        json_vars_file: ${{ inputs.json-vars-file }}
-        json_vars_field: ${{ inputs.json-vars-field }}
-        next_release_version: ${{ steps.set-next-release.outputs.next-release-version }}
-
-    - name: Commit the changes to the '${{ inputs.json-vars-file }}' file
-      id: commit-json-version-changes
-      # probably want to only try to commit changes if 'does_next_match_updated' is 'true'
-      #if: ( '${{ steps.get-updated-version.outputs.does_next_match_updated }}' == 'true' )
-      #uses: stefanzweifel/git-auto-commit-action@v4
-      #uses: EndBug/add-and-commit@v9
-      uses: rwaight/actions/git/add-and-commit@main
-      with:
-        add: ${{ inputs.json-vars-file }}
-        author_name: ${{ inputs.author_name }}
-        author_email: ${{ inputs.author_email }}
-        commit: --signoff
-        committer_name: ${{ inputs.committer_name }}
-        committer_email: ${{ inputs.committer_email }}
-        default_author: ${{ inputs.default_author }}
-        message: '[bump-json-version] Bump ${{ inputs.json-vars-field }} to ${{ steps.set-next-release.outputs.next-release-version }}'
-        # options below are for 'stefanzweifel/git-auto-commit-action'
-        #commit_message: Bump ${{ inputs.json-vars-field }} to ${{ steps.set-next-release.outputs.next-release-version }}
-        #commit_options: '--signoff'
-        #file_pattern: ${{ inputs.json-vars-file }}
-        #branch: '${{ github.ref_name }}'
-        #create_branch: false
-        #commit_user_name: ${{ inputs.gh-user-name }}
-        #commit_user_email: ${{ inputs.gh-user-email }}
+        if [ '${{ inputs.my_action_debug }}' == 'true' ]; then echo "completing the 'validate-version-not-matched' step. "; fi
+      env: 
+        current-release-version: ${{ steps.get-current-release.outputs.current-release-version }}
+        next-release-version: ${{ steps.set-next-release.outputs.next-release-version }}
+        does-current-match-next: ${{ steps.compare-current-to-next-release.outputs.does-current-match-next }}
 
     - name: Debug | Print the outputs
       if: inputs.my_action_debug=='true'
@@ -478,35 +349,18 @@ runs:
         ##
         echo "starting the 'debug-print-outputs' step. "
         echo ""
-        echo "Current release and old JSON version information: "
-        echo "old-json-version is       :  ${{ env.old-json-version }} "
+        echo "Current release version information: "
         echo "current-release-version is:  ${{ env.current-release-version }} "
         echo ""
-        echo "Next release and new JSON version information: "
-        echo "next-release-version is   :  ${{ env.next-release-version }} "
-        echo "new-json-version is       :  ${{ env.new-json-version }} "
+        echo "Next release version information: "
+        echo "next-release-version is:  ${{ env.next-release-version }} "
         echo ""
         echo "Version match results: "
-        echo "do_current_versions_match is:  ${{ env.do_current_versions_match }} "
-        echo "does_current_match_next is  :  ${{ env.does_current_match_next }} "
-        echo "does_next_match_updated is  :  ${{ env.does_next_match_updated }} "
+        echo "does-current-match-next is:  ${{ env.does-current-match-next }} "
         echo ""
         ##
         echo "completing the 'debug-print-outputs' step. "
       env:
         current-release-version: ${{ steps.get-current-release.outputs.current-release-version }}
         next-release-version: ${{ steps.set-next-release.outputs.next-release-version }}
-        old-json-version: ${{ steps.get-current-version.outputs.old-json-version }}
-        new-json-version: ${{ steps.get-updated-version.outputs.new-json-version }}
-        do_current_versions_match: ${{ steps.compare-current-versions.outputs.do_current_versions_match }}
-        does_current_match_next: ${{ steps.compare-current-to-next-release.outputs.does_current_match_next }}
-        does_next_match_updated: ${{ steps.get-updated-version.outputs.does_next_match_updated }}
-
-    # - name: Modify a JSON key value in place
-    #   id: update-json-in-place
-    #   shell: bash
-    #   run: |
-    #     echo "special thanks to this person on stack overflow ... "
-    #     echo "https://stackoverflow.com/questions/42716734/modify-a-key-value-in-a-json-using-jq-in-place "
-    #     tmp=$(mktemp)
-    #     jq '.my_custom_version = "ami-02d8sdfsdf"' my-custom-variables.json > "$tmp" && mv "$tmp" my-custom-variables.json
+        does-current-match-next: ${{ steps.compare-current-to-next-release.outputs.does-current-match-next }}
