refactor: update wildcard semver match attempts

diff --git a/builders/set-version/action.yml b/builders/set-version/action.yml
--- a/builders/set-version/action.yml
+++ b/builders/set-version/action.yml
@@ -469,8 +469,36 @@ runs:
       run: |
         echo "::group::starting the 'wildcard-semver' step... "
         ## old wildcard-semver match ##git describe --tags --match "v[0-9]*.[0-9]*.[0-9]*"
+        if [ '${{ inputs.VERBOSE }}' == 'true' ]; then echo "  verbose - issuing 'set +e' to ignore errors... "; fi
+        set +e
+        echo "  attempt 1 of 3 to set 'semver_wildcard' ... "
         git describe --tags --match "v[0-9*].[0-9*].[0-9*]"
-        semver_wildcard=$(git describe --tags --match "v[0-9*].[0-9*].[0-9*]")
+        exitcode="$?"
+        ##if [[ $? -eq 0 ]]; then
+        if [[ $exitcode -eq 0 ]]; then
+            semver_wildcard=$(git describe --tags --match "v[0-9*].[0-9*].[0-9*]")
+            ##if [ '${{ inputs.VERBOSE }}' == 'true' ]; then echo "  verbose - attempt 1 of 3, 'semver_wildcard' is set to '$semver_wildcard' "; fi
+            echo "    attempt 1 of 3, 'semver_wildcard' is set to '$semver_wildcard' "
+        else
+            echo ""
+            echo "  attempt 2 of 3 to set 'semver_wildcard', using the old wildcard-semver match ... "
+            semver_wildcard=$(git describe --tags --match "v[0-9]*.[0-9]*.[0-9]*")
+            ##if [ '${{ inputs.VERBOSE }}' == 'true' ]; then echo "  verbose - attempt 2 of 3, 'semver_wildcard' is set to '$semver_wildcard' "; fi
+            echo "    attempt 2 of 3, 'semver_wildcard' is set to '$semver_wildcard' "
+        fi
+        ##
+        if [[ -n "$semver_wildcard" ]]; then
+            ##if [ '${{ inputs.VERBOSE }}' == 'true' ]; then echo "  verbose - the variable 'semver_wildcard' is set to '$semver_wildcard' "; fi
+            echo "the variable 'semver_wildcard' is set to '$semver_wildcard' "
+        else
+            echo "the variable 'semver_wildcard' is empty, it is currently set to '$semver_wildcard' "
+            echo ""
+            echo "  attempt 3 of 3 to set 'semver_wildcard', going to add a prefix wildcard ... "
+            semver_wildcard=$(git describe --tags --match "*v[0-9*].[0-9*].[0-9*]")
+            ##if [ '${{ inputs.VERBOSE }}' == 'true' ]; then echo "  verbose - attempt 3 of 3, 'semver_wildcard' is set to '$semver_wildcard' "; fi
+            echo "    attempt 3 of 3, 'semver_wildcard' is set to '$semver_wildcard' "
+        fi
+        ##
         echo "setting the value of 'wildcard-semver' to '${semver_wildcard}' and sending it to GitHub output"
         echo "wildcard-semver=${semver_wildcard}" >> $GITHUB_ENV
         echo "wildcard-semver=${semver_wildcard}" >> $GITHUB_OUTPUT
